[package]
name = "oneshot_aist"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
derive-new = { version = "0.7.0" }
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
fmt-derive = "0.1.2"
thiserror = { version = "2.0.11" }
helpful = { workspace = true }
async-openai = { version = "0.28.0" }
stub-macro = "0.1.6"
tempfile = "3.16.0"
itertools = "0.14.0"
subtype = { git = "https://github.com/DenisGorbachev/subtype" }
tokio = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
url = "2.5.4"
#figment = { version = "0.10.19", features = ["test", "toml"] }
xshell = { version = "0.3.0-pre.2" }
ra_ap_syntax = "0.0.277"
ra_ap_text_edit = "0.0.241"


[package.metadata.cargo-machete]
ignored = ["stub-macro"]
